#!/bin/bash
# 1. Update Golden Apples
sed -i 's/<button class="market-card-btn" onclick="addToCart('\''Golden Apples'\'', 0.45, '\''Farruh M.'\'')">/<div style="margin-top:0.8rem;padding:0.4rem;border-radius:6px;background:#ECFDF5;color:#059669;font-size:0.75rem;font-weight:600;display:flex;align-items:center;gap:0.4rem;"><i class="fa-solid fa-truck-fast"><\/i> Seller offers delivery<\/div>\n                        <button class="market-card-btn" onclick="addToCart('\''Golden Apples'\'', 0.45, '\''Farruh M.'\'', '\''+998901234567'\'', true)">/g' index.html

# 2. Update Navot Melons 
sed -i 's/<button class="market-card-btn" onclick="addToCart('\''Navot Melons'\'', 0.80, '\''Ali N.'\'')">/<div style="margin-top:0.8rem;padding:0.4rem;border-radius:6px;background:#EFF6FF;color:#2563EB;font-size:0.75rem;font-weight:600;display:flex;align-items:center;gap:0.4rem;"><i class="fa-solid fa-user-clock"><\/i> Requires driver assignment<\/div>\n                        <button class="market-card-btn" onclick="addToCart('\''Navot Melons'\'', 0.80, '\''Ali N.'\'', '\''+998939876543'\'', false)">/g' index.html

# 3. Update Red Tomatoes
sed -i 's/<button class="market-card-btn" onclick="addToCart('\''Red Tomatoes'\'', 0.30, '\''Dilshod T.'\'')">/<div style="margin-top:0.8rem;padding:0.4rem;border-radius:6px;background:#EFF6FF;color:#2563EB;font-size:0.75rem;font-weight:600;display:flex;align-items:center;gap:0.4rem;"><i class="fa-solid fa-user-clock"><\/i> Requires driver assignment<\/div>\n                        <button class="market-card-btn" onclick="addToCart('\''Red Tomatoes'\'', 0.30, '\''Dilshod T.'\'', '\''+998993214567'\'', false)">/g' index.html

# 4. Update Yellow Onions
sed -i 's/<button class="market-card-btn" onclick="addToCart('\''Yellow Onions'\'', 0.20, '\''Otabek Z.'\'')">/<div style="margin-top:0.8rem;padding:0.4rem;border-radius:6px;background:#ECFDF5;color:#059669;font-size:0.75rem;font-weight:600;display:flex;align-items:center;gap:0.4rem;"><i class="fa-solid fa-truck-fast"><\/i> Seller offers delivery<\/div>\n                        <button class="market-card-btn" onclick="addToCart('\''Yellow Onions'\'', 0.20, '\''Otabek Z.'\'', '\''+998918887766'\'', true)">/g' index.html

# 5. Fix Harvest Producer Checkbox
sed -i 's/<button type="submit"/<div style="margin-bottom:1.5rem;display:flex;align-items:center;gap:0.5rem;">\n                        <input type="checkbox" id="harvest-transport" style="width:1rem;height:1rem;accent-color:var(--agro-green);">\n                        <label for="harvest-transport" style="font-size:0.85rem;color:var(--text-primary);cursor:pointer;">\n                            I can transport this myself <span style="color:var(--text-secondary);">(Include transport fee in price)<\/span>\n                        <\/label>\n                    <\/div>\n                    <button type="submit"/g' index.html

# 6. Fix Driver Job Board HTML
sed -i 's/<!-- Delivery List -->/<!-- Available Transport Jobs (Dynamically Populated) -->\n                    <div class="content-card" style="margin-bottom: 1.5rem;" id="available-freight-container">\n                        <div class="content-card-header">\n                            <span class="content-card-title"><i class="fa-solid fa-box-open" style="color:var(--harvest-amber);margin-right:0.5rem;"><\/i>Available Transport Jobs<\/span>\n                            <span class="content-card-badge" id="freight-badge" style="background:#FFFBEB;color:var(--harvest-amber);display:none;">0 New<\/span>\n                        <\/div>\n                        <div id="freight-list">\n                            <div style="text-align:center;padding:1rem;color:var(--text-secondary);font-size:0.85rem;" id="no-freight-msg">\n                                No available jobs at the moment.\n                            <\/div>\n                        <\/div>\n                    <\/div>\n\n                    <!-- Delivery List -->/g' index.html

