#!/bin/bash
sed -i 's/function addToCart(name, price, seller) {/function addToCart(name, price, seller, phone = "+998XXXXXXXXX", producerTransport = false) {/g' index.html
sed -i 's/cart.push({ name, price, seller, quantity: 100 });/cart.push({ name, price, seller, phone, producerTransport, quantity: 100 });/g' index.html

# Replace proceedToEscrow block with confirmPayment logic
awk '
/let cartTotalValue = 0;/ { p = 1 }
/function proceedToEscrow()/ {
  if (!p) {
    print "        let cartTotalValue = 0;";
    print "";
    print "        function openPaymentModal() {";
    print "            if (cart.length === 0) {";
    print "                showToast('\''Cart is empty!'\'', '\''error'\'');";
    print "                return;";
    print "            }";
    print "            ";
    print "            // Calculate total for payment modal";
    print "            cartTotalValue = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);";
    print "            document.getElementById('\''payment-total'\'').innerText = '\''$'\'' + cartTotalValue.toFixed(2);";
    print "            ";
    print "            closeCartModal();";
    print "            document.getElementById('\''payment-modal'\'').classList.add('\''open'\'');";
    print "        }";
    print "";
    print "        function closePaymentModal() {";
    print "            document.getElementById('\''payment-modal'\'').classList.remove('\''open'\'');";
    print "        }";
    print "";
    print "        function confirmPayment() {";
    print "            const btn = document.getElementById('\''confirm-payment-btn'\'');";
    print "            const originalText = btn.innerHTML;";
    print "            ";
    print "            // Show loading state";
    print "            btn.innerHTML = '\''<i class=\"fa-solid fa-spinner fa-spin\"></i> Processing Payment...'\'';";
    print "            btn.style.opacity = '\''0.8'\'';";
    print "            btn.disabled = true;";
    print "            ";
    print "            setTimeout(() => {";
    print "                let driverJobCreated = false;";
    print "                ";
    print "                // Generate deals & jobs for each item";
    print "                cart.forEach(item => {";
    print "                    const dealId = '\''deal-'\'' + Math.floor(Math.random() * 10000);";
    print "                    ";
    print "                    // 1. Setup new chat interface for the deal";
    print "                    setupNewDealChat(item, dealId);";
    print "                    ";
    print "                    // 2. If producer doesn'\''t handle transport, post to Driver board";
    print "                    if (!item.producerTransport) {";
    print "                        postToDriverBoard(item, dealId);";
    print "                        driverJobCreated = true;";
    print "                    }";
    print "                });";
    print "";
    print "                closePaymentModal();";
    print "                btn.innerHTML = originalText;";
    print "                btn.style.opacity = '\''1'\'';";
    print "                btn.disabled = false;";
    print "                ";
    print "                cart = []; // Clear cart";
    print "";
    print "                const badge = document.getElementById('\''cart-badge'\'');";
    print "                if (badge) {";
    print "                    badge.innerText = '\''0'\'';";
    print "                    badge.style.display = '\''none'\'';";
    print "                }";
    print "";
    print "                showToast('\''Payment successful! Escrow initialized.'\'', '\''success'\'', 2000);";
    print "                ";
    print "                if (driverJobCreated) {";
    print "                    setTimeout(() => {";
    print "                        showToast('\''Driver network notified of new available job!'\'', '\''info'\'', 3000);";
    print "                    }, 500);";
    print "                }";
    print "";
    print "                setTimeout(() => {";
    print "                    switchView('\''messages'\'');";
    print "                }, 1500);";
    print "                ";
    print "            }, 1200); // Simulate network delay";
    print "        }";
    print "";
    print "        // --- Checkout Flow Helpers ---";
    print "        function setupNewDealChat(item, dealId) {";
    print "            const list = document.getElementById('\''deal-groups-list'\'');";
    print "            const totalEscrow = (item.price * item.quantity).toFixed(2);";
    print "            ";
    print "            // 1. Add to Sidebar Left";
    print "            const sidebarHTML = \`";
    print "                <div class=\"chat-contact\" onclick=\"document.querySelectorAll('\'.chat-contact\').forEach(el=>el.classList.remove('\''active'\'')); this.classList.add('\''active'\'');\" style=\"animation: fadeInUp 0.4s ease forwards;\">";
    print "                    <div class=\"contact-avatar\" style=\"background:#ECFDF5;color:#059669;\">";
    print "                        <i class=\"fa-solid fa-leaf\"></i>";
    print "                    </div>";
    print "                    <div class=\"contact-info\">";
    print "                        <div class=\"contact-name\">\${item.seller}</div>";
    print "                        <div class=\"contact-preview\">Order: \${item.quantity}kg \${item.name}</div>";
    print "                    </div>";
    print "                </div>";
    print "            \`;";
    print "            list.insertAdjacentHTML('\''afterbegin'\'', sidebarHTML);";
    print "";
    print "            // 2. Populate Chat Body dynamically";
    print "            // Overwriting existing chat display for simulation purposes";
    print "            const chatBodyHTML = \`";
    print "                <div class=\"message system\">";
    print "                    <div class=\"system-inner\">";
    print "                        <i class=\"fa-solid fa-shield-halved\" style=\"color:var(--accent-blue);font-size:1.2rem;margin-bottom:0.5rem;\"></i>";
    print "                        <h4 style=\"margin:0 0 0.5rem 0;color:var(--text-primary);\">Escrow Transaction Initialized</h4>";
    print "                        <p style=\"margin:0;font-size:0.85rem;\">";
    print "                            <strong>Order:</strong> \${item.quantity} kg \${item.name}<br>";
    print "                            <strong>Escrow Held:</strong> $\${totalEscrow} (Funds are secured until delivery)<br>";
    print "                            <strong>Seller Phone:</strong> \${item.phone}<br>";
    print "                            <strong>Transport:</strong> \${item.producerTransport ? '\''Handled by Seller'\'' : '\''Awaiting Driver Assignment'\''}";
    print "                        </p>";
    print "                    </div>";
    print "                </div>";
    print "                ";
    print "                <div class=\"message received\" style=\"animation: fadeInUp 0.3s ease forwards; animation-delay: 0.5s; opacity:0;\">";
    print "                    <div class=\"msg-avatar\" style=\"background:#ECFDF5;color:#059669;\">";
    print "                        <i class=\"fa-solid fa-leaf\"></i>";
    print "                    </div>";
    print "                    <div class=\"msg-bubble\">";
    print "                        Assalomu alaykum! I have received your secure escrow deposit for $\${totalEscrow}. The \${item.name} are ready for pickup.";
    print "                        <div class=\"msg-time\">Just now</div>";
    print "                    </div>";
    print "                </div>";
    print "            \`;";
    print "            ";
    print "            const chatBody = document.getElementById('\''chat-body'\'');";
    print "            if (chatBody) {";
    print "                // Remove placeholder messages, leave date header";
    print "                const items = Array.from(chatBody.children);";
    print "                items.forEach(el => {";
    print "                    if(!el.classList.contains('\''chat-date-divider'\'')) el.remove();";
    print "                });";
    print "                chatBody.insertAdjacentHTML('\''beforeend'\'', chatBodyHTML);";
    print "                // Trigger reflow & jump to bottom";
    print "                setTimeout(() => { chatBody.scrollTop = chatBody.scrollHeight; }, 100);";
    print "            }";
    print "        }";
    print "";
    print "        function postToDriverBoard(item, dealId) {";
    print "            const container = document.getElementById('\''freight-list'\'');";
    print "            const badge = document.getElementById('\''freight-badge'\'');";
    print "            const noMsg = document.getElementById('\''no-freight-msg'\'');";
    print "            ";
    print "            if (noMsg) noMsg.style.display = '\''none'\'';";
    print "            ";
    print "            // Random route for simulation";
    print "            const routes = [\"Samarkand &rarr; Tashkent\", \"Fergana &rarr; Andijan\", \"Bukhara &rarr; Navoi\"];";
    print "            const route = routes[Math.floor(Math.random() * routes.length)];";
    print "            const payout = Math.floor(item.quantity * 0.12); // ~12c per kg driver payout simulation";
    print "";
    print "            const jobHTML = \`";
    print "                <div class=\"placeholder-row\" id=\"\${dealId}\" style=\"animation: fadeInUp 0.4s ease forwards;\">";
    print "                    <div class=\"placeholder-avatar\" style=\"background:var(--harvest-amber);color:white;\">";
    print "                        <i class=\"fa-solid fa-sack-dollar\"></i>";
    print "                    </div>";
    print "                    <div class=\"placeholder-text\">";
    print "                        <div class=\"name\">\${item.quantity} kg \${item.name}</div>";
    print "                        <div class=\"desc\">\${route} &bull; Driver Payout: $\${payout}</div>";
    print "                    </div>";
    print "                    <button onclick=\"acceptFreight('\''\${dealId}'\'', '\''\${item.name}'\'')\" style=\"padding: 0.4rem 0.8rem; border-radius: 8px; border: none; background: var(--agro-green); color: white; font-weight: 600; cursor: pointer; font-size: 0.75rem; transition: background 0.2s;\">";
    print "                        Accept Load";
    print "                    </button>";
    print "                </div>";
    print "            \`;";
    print "            ";
    print "            if (container) {";
    print "                container.insertAdjacentHTML('\''afterbegin'\'', jobHTML);";
    print "            }";
    print "            ";
    print "            if (badge) {";
    print "                let current = parseInt(badge.innerText) || 0;";
    print "                badge.innerText = \`\${current + 1} New\`;";
    print "                badge.style.display = '\''inline-flex'\'';";
    print "            }";
    print "        }";
    skip = 1;
  }
}
/^    <\/script>/ { skip = 0 }
!skip { print }
' index.html > temp.html && mv temp.html index.html

